# Generated by Django 6.0.2 on 2026-02-19 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=200)),
                ('participant_id', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('caregiver_name', models.CharField(max_length=200)),
                ('house_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('house_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='centers.projectcenter')),
            ],
        ),
    ]
