# Generated by Django 6.0.2 on 2026-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_alter_participant_house_latitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['project_center'], name='centers_par_project_6eec2a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['participant_id'], name='centers_par_partici_9badc5_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['project_center', 'participant_id'], name='centers_par_project_abb99b_idx'),
        ),
    ]
